---
abstract: 'Create CPAN::Mini mirror with developer releases'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::More: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Mini-Devel
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Mini::Devel:
    file: lib/CPAN/Mini/Devel.pm
    version: '0.04'
requires:
  CPAN: '1.92'
  CPAN::HandleConfig: '0'
  CPAN::Mini: '0.567'
  CPAN::Tarzip: '0'
  File::Basename: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0.20'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/CPAN-Mini-Devel/issues
  homepage: https://github.com/dagolden/CPAN-Mini-Devel
  repository: https://github.com/dagolden/CPAN-Mini-Devel.git
version: '0.04'
x_authority: cpan:DAGOLDEN
